//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int idAgent { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
