//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAdress
    {
        public CustomerAdress()
        {
            this.Machine = new HashSet<Machine>();
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int idCustomerAdress { get; set; }
        public string City { get; set; }
        public string AdressLine1 { get; set; }
        public string Representant { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int idCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
