//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAdress = new HashSet<CustomerAdress>();
        }
    
        public int idCustomer { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CustomerAdress> CustomerAdress { get; set; }
    }
}
