//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.ServiceFile = new HashSet<ServiceFile>();
        }
    
        public int idMachine { get; set; }
        public int idCustomerAdress { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual CustomerAdress CustomerAdress { get; set; }
        public virtual ICollection<ServiceFile> ServiceFile { get; set; }
    }
}
