//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOperation
    {
        public int idServiceOperation { get; set; }
        public int idOperation { get; set; }
        public int idServiceFile { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual ServiceFile ServiceFile { get; set; }
    }
}
