//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFile
    {
        public ServiceFile()
        {
            this.ServiceOperation = new HashSet<ServiceOperation>();
            this.UsedSpare = new HashSet<UsedSpare>();
        }
    
        public int idServiceFile { get; set; }
        public int idWorkOrder { get; set; }
        public int idMachine { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual ICollection<ServiceOperation> ServiceOperation { get; set; }
        public virtual ICollection<UsedSpare> UsedSpare { get; set; }
    }
}
