//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagaziaSculeEntities : DbContext
    {
        public MagaziaSculeEntities()
            : base("name=MagaziaSculeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agent> Agent { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<CustomerAdress> CustomerAdress { get; set; }
        public DbSet<Machine> Machine { get; set; }
        public DbSet<Operation> Operation { get; set; }
        public DbSet<ServiceFile> ServiceFile { get; set; }
        public DbSet<ServiceOperation> ServiceOperation { get; set; }
        public DbSet<SparePart> SparePart { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UsedSpare> UsedSpare { get; set; }
        public DbSet<WorkOrder> WorkOrder { get; set; }
    }
}
