//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolshed
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.ServiceFile = new HashSet<ServiceFile>();
        }
    
        public int idWorkOrder { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool Approved { get; set; }
        public bool Sent { get; set; }
        public Nullable<int> Rating { get; set; }
        public bool Closed { get; set; }
        public Nullable<int> idCustomerAdress { get; set; }
        public Nullable<int> idAgent { get; set; }
        public string idServiceFile { get; set; }
        public Nullable<int> CustomTime { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual CustomerAdress CustomerAdress { get; set; }
        public virtual ICollection<ServiceFile> ServiceFile { get; set; }
    }
}
